src/lib.rs
tests/web.rs

Use EitherEd25519SecretKey for PrivateKey
Fix wrong type in TransactionBuilderCertificate
Add balance without fee
Add OutputPolicy, SpendingCounter, Witness and Input constructors from account

Add TransactionFinalizer - Account wrapper - Witness wrapper

---

README.md

Add build command to the readme

change template readme

---

.gitignore
Cargo.toml
package.json
src/lib.rs
tests/index.js
tests/web.rs
webpack.config.js

Add webpack and tests/index.js as an example and to do some testing
Note: This shouldn't me merged before [this PR](https://github.com/input-output-hk/js-chain-libs/pull/3)

Add javascript webpack example

---

package.json
src/lib.rs
tests/index.js

There was some errors in the example
Add assert instead of comparing values

Improve fix js test

---

src/lib.rs

Update submodule and change the function signatures accordingly

string-anyprefix change

---

src/lib.rs

Reverts input-output-hk/js-chain-libs#6

Revert "string-anyprefix change"

---

src/lib.rs
tests/web.rs

Create addresses from public keys
Fix some tests
Fix some lints

Address from public key

---

README.md

Add example of how to make a simple transaction to the readme
Show possible webpack config

add working example to the readme

---

src/lib.rs
webpack.config.js

For some reason I didn't include that change in the previous PR, so the js tests were not actually loaded.

Fix mocha webpack loader regex

---

Cargo.toml
src/lib.rs
tests/web.rs

Random generation functions for private keys, I based this on the ones from the jcli... I'm not sure if an optional seed is needed.

Random key generation

---

README.md

Improve a few things confusing things.

Fix readme multiline requirements

---

examples/faucet/README.md

add comment about env file creation to readme

---

examples/faucet/README.md

clarify directories in faucet example

---

README.md

relates to #25 
the browser part should be solved by #28

add example logged value little explanation

---

examples/explorer/.eslintrc
examples/explorer/README.md
examples/explorer/data/schema.graphql
examples/explorer/relay.config.js
examples/explorer/src/App.jsx
examples/explorer/src/components/Addresses/AddressInfo/AddressInfo.jsx
examples/explorer/src/components/Blocks/BlockInfo/BlockInfo.jsx
examples/explorer/src/components/Blocks/BlockTable/BlockTable.jsx
examples/explorer/src/components/Blocks/BlockTablePage/BlockTablePage.jsx
examples/explorer/src/components/Blocks/RecentBlocks/RecentBlocks.jsx
examples/explorer/src/components/Certificates/CertificateInfo/CertificateInfo.jsx
examples/explorer/src/components/Certificates/OwnerStakeDelegation/OwnerStakeDelegation.jsx
examples/explorer/src/components/Certificates/PoolRegistration/PoolRegistration.jsx
examples/explorer/src/components/Certificates/StakeDelegation/StakeDelegation.jsx
examples/explorer/src/components/Commons/TransactionLink/TransactionLink.jsx
examples/explorer/src/components/Epochs/EpochInfo/EpochInfo.jsx
examples/explorer/src/components/MainNavbar/MainNavbar.jsx
examples/explorer/src/components/Search/SearchBar/SearchBar.jsx
examples/explorer/src/components/Status/Cards/BlockCard/BlockCard.jsx
examples/explorer/src/components/Status/Cards/EpochCard/EpochCard.jsx
examples/explorer/src/components/Status/Cards/FeeCard/FeeCard.jsx
examples/explorer/src/components/Status/StatusInfo/StatusInfo.jsx
examples/explorer/src/components/Transactions/TransactionInfo/TransactionInfo.jsx
examples/explorer/src/helpers/constants.js

This PR contains:
- Adding information on Readme.
- Recent blocks component.Showing all blocks.

Adding recent blocks component to explorer

---

src/lib.rs

Reverts input-output-hk/js-chain-libs#57
That PR depends on https://github.com/input-output-hk/chain-libs/pull/118 which is not yet merged

Revert "Add sign&verify and external witnesses"

---

examples/explorer/data/schema.graphql
examples/explorer/src/App.jsx
examples/explorer/src/components/Address/FullAddressInfo/FullAddressInfo.jsx
examples/explorer/src/components/Block/BlockInfo/BlockInfo.jsx
examples/explorer/src/components/Block/BlockTable/BlockTable.jsx
examples/explorer/src/components/Block/FullBlockInfo/FullBlockInfo.jsx
examples/explorer/src/components/Block/RecentBlocksTable/RecentBlocksTable.jsx
examples/explorer/src/components/Certificate/OwnerStakeDelegation/OwnerStakeDelegation.jsx
examples/explorer/src/components/Certificate/PoolRegistration/PoolRegistration.jsx
examples/explorer/src/components/Certificate/StakeDelegation/StakeDelegation.jsx
examples/explorer/src/components/Commons/DateTime/DateTime.jsx
examples/explorer/src/components/Commons/EmptyResult/EmptyResult.jsx
examples/explorer/src/components/Commons/NextPrev/NextPrev.jsx
examples/explorer/src/components/Commons/NotFound/NotFound.jsx
examples/explorer/src/components/Commons/NotFound/notFound.scss
examples/explorer/src/components/Commons/index.js
examples/explorer/src/components/Epoch/EpochBlockTable/EpochBlockTable.jsx
examples/explorer/src/components/StakePool/StakePoolBlockTable/StakePoolBlockTable.jsx
examples/explorer/src/components/Transaction/AddressTransactionTable/AddressTransactionTable.jsx
examples/explorer/src/components/Transaction/BlockTransactionTable/BlockTransactionTable.jsx
examples/explorer/src/components/Transaction/TransactionTable/TransactionTable.jsx
examples/explorer/src/components/Transaction/index.js
examples/explorer/src/config.json
examples/explorer/src/graphql/queries/allBlocks.js
examples/explorer/src/helpers/blockHelper.js
examples/explorer/src/helpers/datetimeHelper.js
examples/explorer/src/helpers/epochHelper.js

This PR contains:
- Adding transaction pagination.
- Replacing all Cursor-based tables with Offset-based tables.
- Fixing minor bugs.
Dependent on input-output-hk/jormungandr#1035

Explorer adding transaction pagination

---

examples/explorer/data/schema.graphql
examples/explorer/src/components/Certificate/OwnerStakeDelegation/OwnerStakeDelegation.jsx
examples/explorer/src/components/Certificate/StakeDelegation/StakeDelegation.jsx

Update schema and UI to https://github.com/input-output-hk/jormungandr/pull/1084
With this PR, multidelegation certificates show all the pools (in the simplest way possible)
@dmernies-iohk what do you think?

Update schema with multidelegation

---

examples/wallet/.eslintrc.json
examples/wallet/README.md
examples/wallet/app/actions/account.js
examples/wallet/app/actions/nodeSettings.js
examples/wallet/app/actions/stakePools.js
examples/wallet/app/app.global.scss
examples/wallet/app/components/AccountInfo.js
examples/wallet/app/components/AccountInfo.scss
examples/wallet/app/components/TransactionListing.js
examples/wallet/app/components/TransactionListing.scss
examples/wallet/app/containers/AccountInfo.js
examples/wallet/app/containers/Root.js
examples/wallet/app/containers/TransactionListing.js
examples/wallet/app/layouts/SidebarLayout.js
examples/wallet/app/layouts/SidebarLayout.scss
examples/wallet/app/models/index.js
examples/wallet/app/pages/Wallet.js
examples/wallet/app/reducers/account.js
examples/wallet/app/reducers/types.js
examples/wallet/app/utils/nodeConnection.js
examples/wallet/app/utils/wasmWrapper.js
examples/wallet/config/default.json
examples/wallet/package.json

this PR is big enough as it is, transaction details dropdown, date and confirmation status will be separate PRs

Wallet - add transaction listing

---

.babelrc
.circleci/config.yml
package.json

Simplistic way of running the javascript tests with node on circle.

Run js tests in node

---

examples/wallet/app/Routes.js
examples/wallet/app/actions/account.js
examples/wallet/app/actions/nodeSettings.js
examples/wallet/app/actions/router.js
examples/wallet/app/containers/ChooseRestoreOrImport.js
examples/wallet/app/containers/Index.js
examples/wallet/app/containers/InputKeys.js
examples/wallet/app/containers/SidebarLayout.js
examples/wallet/app/layouts/SidebarLayout.js
examples/wallet/app/pages/ChooseRestoreOrImport.js
examples/wallet/app/pages/Delegate.js
examples/wallet/app/pages/Index.js
examples/wallet/app/pages/InputKeys.js
examples/wallet/app/pages/Send.js
examples/wallet/app/pages/Settings.js
examples/wallet/app/pages/Wallet.js
examples/wallet/app/reducers/index.js
examples/wallet/app/reducers/types.js
examples/wallet/yarn.lock

refactored uses of `react-router` to consistently use the redux bindings of `react-connected-router`
depends on: https://github.com/input-output-hk/js-chain-libs/pull/99

More consistent react router usage

---

examples/wallet/app/utils/nodeConnection.js
examples/wallet/yarn.lock

tested against jormungandr v0.7.1

update graphql call

---

examples/wallet/app/actions/account.js
examples/wallet/app/actions/nodeSettings.js
examples/wallet/app/actions/router.js
examples/wallet/app/pages/InputKeys.js
examples/wallet/app/utils/nodeConnection.js
examples/wallet/app/utils/storage.js

Read and write data in local storage is added so that you don't have to import or create a key every time it starts. It works with jormungandr 0.8.0-rc10

Wallet adding local storage account info

---

examples/wallet/.eslintrc.json
examples/wallet/app/actions/account.js
examples/wallet/app/components/SendTransaction.js
examples/wallet/app/components/StakeDelegation.js
examples/wallet/app/containers/SendTransaction.js
examples/wallet/app/containers/StakeDelegation.js
examples/wallet/app/reducers/account.js
examples/wallet/app/reducers/types.js
examples/wallet/test/actions/account.spec.js

depends on: https://github.com/input-output-hk/js-chain-libs/pull/111
I'll try to make unit tests for:
- [ x ] action
- [  ] reducer
- [  ] form
- [  ] related chainlib function
I'd also like to try making e2e or integration tests, but that'll probably be best reserved for a future PR.
Integration with CircleCI might or might not make it into this PR

Wallet: test send funds action

---

examples/wallet/app/reducers/account.js
examples/wallet/test/reducers/account.spec.js

depends on: https://github.com/input-output-hk/js-chain-libs/pull/114

Wallet test send funds reducer

---

examples/wallet/test/components/__snapshots__/SendTransaction.spec.js.snap

I forgot to update a snapshot 🙃

fix send fund form tests

---

src/lib.rs

Need to be able to serialize inputs for Yoroi so I added these functions
**Note 1:** This includes a breaking change where `get_type` now returns an enum. This matches the pattern with the rest of the codebase
**Note 2:** I didn't add similar functions for `Output` because it looks like chain-libs doesn't have a serialization format for outputs and probably that's something the Rust team needs to decide and not me.

Add as_bytes and from_bytes for Input

---

PULL_REQUEST_TEMPLATE.md

This pull request modifies the:
Developed against jormungandr version: [non applicable]
Changes introduced:
- [  ] Added a PR template
Breaking changes:
none

created pull request template

---

Cargo.toml
src/lib.rs
src/transaction/txbuilder.rs

This pull request modifies the:

update chain-deps to latest

---

src/lib.rs
src/transaction/iobuilder.rs
src/transaction/mod.rs
src/transaction/txbuilder.rs

This pull request modifies the:
Changes introduced:
Update the submodule
Breaking changes:
None

Update chain libs add vote
